# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(1561, 1433)
        dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.graphicsView_Images = QtWidgets.QGraphicsView(dialog)
        self.graphicsView_Images.setGeometry(QtCore.QRect(50, 360, 561, 471))
        self.graphicsView_Images.setObjectName("graphicsView_Images")
        self.Images_label = QtWidgets.QLabel(dialog)
        self.Images_label.setGeometry(QtCore.QRect(260, 310, 114, 33))
        self.Images_label.setObjectName("Images_label")
        self.comboBox_Filters = QtWidgets.QComboBox(dialog)
        self.comboBox_Filters.setGeometry(QtCore.QRect(140, 860, 351, 61))
        self.comboBox_Filters.setObjectName("comboBox_Filters")
        self.comboBox_Filters.addItem("")
        self.comboBox_Filters.addItem("")
        self.comboBox_Filters.addItem("")
        self.comboBox_Filters.addItem("")
        self.comboBox_Filters.addItem("")
        self.comboBox_Filters.addItem("")
        self.comboBox_Filters.addItem("")
        self.comboBox_Filters.addItem("")
        self.comboBox_Filters.addItem("")
        self.comboBox_Filters.addItem("")
        self.comboBox_music = QtWidgets.QComboBox(dialog)
        self.comboBox_music.setGeometry(QtCore.QRect(140, 1080, 311, 61))
        self.comboBox_music.setObjectName("comboBox_music")
        self.comboBox_music.addItem("")
        self.comboBox_music.addItem("")
        self.Image_Search_Label = QtWidgets.QLabel(dialog)
        self.Image_Search_Label.setGeometry(QtCore.QRect(50, 70, 241, 33))
        self.Image_Search_Label.setObjectName("Image_Search_Label")
        self.pushButton_apply = QtWidgets.QPushButton(dialog)
        self.pushButton_apply.setGeometry(QtCore.QRect(90, 970, 187, 57))
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.pushButton_add = QtWidgets.QPushButton(dialog)
        self.pushButton_add.setGeometry(QtCore.QRect(320, 970, 187, 57))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_add_Sound = QtWidgets.QPushButton(dialog)
        self.pushButton_add_Sound.setGeometry(QtCore.QRect(210, 1170, 187, 57))
        self.pushButton_add_Sound.setObjectName("pushButton_add_Sound")
        self.graphicsView_Video = QtWidgets.QGraphicsView(dialog)
        self.graphicsView_Video.setGeometry(QtCore.QRect(670, 350, 821, 631))
        self.graphicsView_Video.setObjectName("graphicsView_Video")
        self.pushButton_Video = QtWidgets.QPushButton(dialog)
        self.pushButton_Video.setGeometry(QtCore.QRect(830, 1000, 187, 57))
        self.pushButton_Video.setObjectName("pushButton_Video")
        self.pushButton_Save = QtWidgets.QPushButton(dialog)
        self.pushButton_Save.setGeometry(QtCore.QRect(1110, 1000, 187, 57))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.pushButton_reset = QtWidgets.QPushButton(dialog)
        self.pushButton_reset.setGeometry(QtCore.QRect(540, 1300, 187, 57))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.pushButton_done = QtWidgets.QPushButton(dialog)
        self.pushButton_done.setGeometry(QtCore.QRect(790, 1300, 187, 57))
        self.pushButton_done.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_done.setObjectName("pushButton_done")
        self.lineEdit_Search = QtWidgets.QLineEdit(dialog)
        self.lineEdit_Search.setGeometry(QtCore.QRect(50, 120, 371, 61))
        self.lineEdit_Search.setObjectName("lineEdit_Search")
        self.Search_Button = QtWidgets.QPushButton(dialog)
        self.Search_Button.setGeometry(QtCore.QRect(470, 120, 187, 57))
        self.Search_Button.setObjectName("Search_Button")
        self.label_Video = QtWidgets.QLabel(dialog)
        self.label_Video.setGeometry(QtCore.QRect(1030, 290, 114, 33))
        self.label_Video.setObjectName("label_Video")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Image to Video Creator"))
        self.Images_label.setText(_translate("dialog", "Images:"))
        self.comboBox_Filters.setItemText(0, _translate("dialog", "Choose a filter"))
        self.comboBox_Filters.setItemText(1, _translate("dialog", "None"))
        self.comboBox_Filters.setItemText(2, _translate("dialog", "Sharpen"))
        self.comboBox_Filters.setItemText(3, _translate("dialog", "Blur"))
        self.comboBox_Filters.setItemText(4, _translate("dialog", "Negative"))
        self.comboBox_Filters.setItemText(5, _translate("dialog", "Posterize"))
        self.comboBox_Filters.setItemText(6, _translate("dialog", "Black & White"))
        self.comboBox_Filters.setItemText(7, _translate("dialog", "Solarize"))
        self.comboBox_Filters.setItemText(8, _translate("dialog", "Thumbnail"))
        self.comboBox_Filters.setItemText(9, _translate("dialog", "Sepia"))
        self.comboBox_music.setItemText(0, _translate("dialog", "Choose Music"))
        self.comboBox_music.setItemText(1, _translate("dialog", "Basic"))
        self.Image_Search_Label.setText(_translate("dialog", "Search for image:"))
        self.pushButton_apply.setText(_translate("dialog", "Apply"))
        self.pushButton_add.setText(_translate("dialog", "Add Image"))
        self.pushButton_add_Sound.setText(_translate("dialog", "Add Sound"))
        self.pushButton_Video.setText(_translate("dialog", "Preview Video"))
        self.pushButton_Save.setText(_translate("dialog", "Save Video"))
        self.pushButton_reset.setText(_translate("dialog", "Reset"))
        self.pushButton_done.setText(_translate("dialog", "Done!"))
        self.Search_Button.setText(_translate("dialog", "Search"))
        self.label_Video.setText(_translate("dialog", "Video:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
